name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    environment: .env
    strategy:
      fail-fast: false
      matrix:
        project: [chrome]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm install
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright Tests
      env:
       ORG_ADMIN_EMAIL: ${{ secrets.ORG_ADMIN_EMAIL }}
       ORG_ADMIN_PASSWORD: ${{ secrets.ORG_ADMIN_PASSWORD }}
       BASE_URL: ${{ secrets.UI_BASE_URL }}
       API_BASE_URL: ${{ secrets.API_BASE_URL }}

       name: Upload Playwright Report

      run: npx playwright test --project=${{ matrix.project }}
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report-${{ matrix.project }}
        path: playwright-report/
        retention-days: 30
